include(testing NO_POLICY_SCOPE)

# include module under test
include(mini.string)

testsuite("mini.string tests")
    test("mini_string_snake_case - simple string")
        set(input "Foo bar baZ")
        set(expected "foo_bar_baz")
        mini_string_snake_case(${input} input)
        assert_str_equal(${input} ${expected})
    endtest()

    test("mini_string_snake_case - strip surrounding whitespaces")
        set(input " Foo bar baZ ")
        set(expected "foo_bar_baz")
        mini_string_snake_case(${input} input)
        assert_str_equal(${input} ${expected})
    endtest()

    test("mini_string_snake_case - strip surrounding whitespaces (non-word chars)")
        set(input "_Foo bar baZ-")
        set(expected "foo_bar_baz")
        mini_string_snake_case(${input} input)
        assert_str_equal(${input} ${expected})
    endtest()

    test("mini_string_snake_case - remove whitespaces")
        set(input "Foo   bar  baZ")
        set(expected "foo_bar_baz")
        mini_string_snake_case(${input} input)
        assert_str_equal(${input} ${expected})
    endtest()

    test("mini_string_snake_case - remove whitespaces (limit 2)")
        set(input "Foo   bar  baZ")
        set(expected "foo__bar__baz")
        mini_string_snake_case(${input} input MAX_SPACES 2)
        assert_str_equal(${input} ${expected})
    endtest()

    test("mini_string_snake_case - simple string with lower mode")
        set(input "Foo bar baZ")
        set(expected "foo_bar_baz")
        mini_string_snake_case(${input} input MODE TOLOWER)
        assert_str_equal(${input} ${expected})
    endtest()

    test("mini_string_snake_case - simple string with upper mode")
        set(input "Foo bar baZ")
        set(expected "FOO_BAR_BAZ")
        mini_string_snake_case(${input} input MODE TOUPPER)
        assert_str_equal(${input} ${expected})
    endtest()


    test("mini_string_pascal_case - simple string")
        set(input "Foo bar baZ")
        set(expected "FooBarBaz")
        mini_string_pascal_case(${input} input)
        assert_str_equal(${input} ${expected})
    endtest()

    test("mini_string_pascal_case - simple string w/ number")
        set(input "Foo1 2bar ba3Z")
        set(expected "Foo12barBa3z")
        mini_string_pascal_case(${input} input)
        assert_str_equal(${input} ${expected})
    endtest()

    test("mini_string_pascal_case - simple string w/ multiple spaces")
        set(input "Foo  bar   baZ")
        set(expected "FooBarBaz")
        mini_string_pascal_case(${input} input)
        assert_str_equal(${input} ${expected})
    endtest()

    test("mini_string_pascal_case - simple string (non-word chars)")
        set(input "Foo$bar_baZ")
        set(expected "FooBarBaz")
        mini_string_pascal_case(${input} input)
        assert_str_equal(${input} ${expected})
    endtest()
    
    test("mini_string_pascal_case - strip surrounding whitespaces")
        set(input " Foo bar baZ  ")
        set(expected "FooBarBaz")
        mini_string_pascal_case(${input} input)
        assert_str_equal(${input} ${expected})
    endtest()

    test("mini_string_pascal_case - strip surrounding whitespaces (non-word chars)")
        set(input "_Foo bar baZ -")
        set(expected "FooBarBaz")
        mini_string_pascal_case(${input} input)
        assert_str_equal(${input} ${expected})
    endtest()
endtestsuite()
