cmake_minimum_required(VERSION 3.30)
include_guard(GLOBAL)

macro(mini_set_default VARIABLE)
    if(NOT ${VARIABLE})
        message(DEBUG "${VARIABLE} is empty or contains a non-true value: '${${VARIABLE}}'")
        if(NOT "${ARGN}" STREQUAL "")
            message(DEBUG "Setting ${VARIABLE} to '${ARGN}'.")
            set(${VARIABLE} "${ARGN}")
        else()
            message(DEBUG "Unsetting ${VARIABLE} because no default was given.")
            unset(${VARIABLE})
        endif()
    endif()
endmacro()
